export const categories = ["action", "drama", "horror", "comedy", "romance"];

export const movieData = [
  {
    name: 'Avengers: Endgame',
    year: 2019,
    img: 'https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SY1000_CR0,0,674,1000_AL_.jpg',
    rate: '9.6',
    category: 'action',
  },
  {
    name: 'Once Upon a Time ... in Hollywood',
    year: 2019,
    img: 'https://m.media-amazon.com/images/M/MV5BOTg4ZTNkZmUtMzNlZi00YmFjLTk1MmUtNWQwNTM0YjcyNTNkXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_SY1000_CR0,0,674,1000_AL_.jpg',
    rate: '8.9',
    category: 'drama',
  },
  {
    name: 'The Conjuring',
    year: 2013,
    img: 'https://m.media-amazon.com/images/M/MV5BMTM3NjA1NDMyMV5BMl5BanBnXkFtZTcwMDQzNDMzOQ@@._V1_SY1000_CR0,0,674,1000_AL_.jpg',
    rate: '8.5',
    category: 'horror',
  },
  {
    name: 'The Hangover',
    year: 2009,
    img: 'https://m.media-amazon.com/images/M/MV5BNGQwZjg5YmYtY2VkNC00NzliLTljYTctNzI5NmU3MjE2ODQzXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX675_CR0,0,675,999_AL_.jpg',
    rate: '8.7',
    category: 'comedy',
  },
  {
    name: 'Terminator: Dark Fate',
    year: 2019,
    img: 'https://m.media-amazon.com/images/M/MV5BNzhlYjE5MjMtZDJmYy00MGZmLTgwN2MtZGM0NTk2ZTczNmU5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX640_CR0,0,640,999_AL_.jpg',
    rate: '8.2',
    category: 'action',
  },
  {
    name: 'John Wick',
    year: 2014,
    img: 'https://m.media-amazon.com/images/M/MV5BMTU2NjA1ODgzMF5BMl5BanBnXkFtZTgwMTM2MTI4MjE@._V1_SY1000_CR0,0,666,1000_AL_.jpg',
    rate: '8.5',
    category: 'action',
  },
  {
    name: 'The Dark Knight',
    year: 2008,
    img: 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SY1000_CR0,0,675,1000_AL_.jpg',
    rate: '9.0',
    category: 'action',
  },
  {
    name: 'The Shawshank Redemption',
    year: 1994,
    img: 'https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg',
    rate: '9.3',
    category: 'drama',
  },
  {
    name: 'The Godfather',
    year: 1972,
    img: 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SY1000_CR0,0,704,1000_AL_.jpg',
    rate: '9.2',
    category: 'drama',
  },
  {
    name: 'The Lord of the Rings: The Return of the King',
    year: 2003,
    img: 'https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SY1000_CR0,0,675,1000_AL_.jpg',
    rate: '8.9',
    category: 'drama',
  },
  {
    name: 'The Exorcist',
    year: 1973,
    img: 'https://m.media-amazon.com/images/M/MV5BYjhmMGMxZDYtMTkyNy00YWVmLTgyYmUtYTU3ZjcwNTBjN2I1XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SY1000_CR0,0,667,1000_AL_.jpg',
    rate: '7.3',
    category: 'horror',
  },
  {
    name: 'The Nun',
    year: 2018,
    img: 'https://m.media-amazon.com/images/M/MV5BMjM3NzQ5NDcxOF5BMl5BanBnXkFtZTgwNzM4MTQ5NTM@._V1_SY1000_CR0,0,674,1000_AL_.jpg',
    rate: '8.8',
    category: 'horror',
  },
  {
    name: 'Halloween',
    year: 1978,
    img: 'https://m.media-amazon.com/images/M/MV5BNzk1OGU2NmMtNTdhZC00NjdlLWE5YTMtZTQ0MGExZTQzOGQyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
    rate: '7.8',
    category: 'horror',
  },
  {
    name: 'The 40-Year-Old Virgin',
    year: 2005,
    img: 'https://m.media-amazon.com/images/M/MV5BMTNjYTA1NDMtZGZmZi00MTdiLThjZTMtZWU1MGYyZjZkNzgxXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SY1000_CR0,0,674,1000_AL_.jpg',
    rate: '8.1',
    category: 'comedy',
  },
  {
    name: 'Step Brothers',
    year: 2008,
    img: 'https://m.media-amazon.com/images/M/MV5BODViZDg3ZjYtMzhiYS00YTVkLTk4MzktYWUxMTlkYjc1NjdlXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SY1000_CR0,0,674,1000_AL_.jpg',
    rate: '7.9',
    category: 'comedy',
  },
  {
    name: '17 Again',
    year: 2009,
    img: 'https://m.media-amazon.com/images/M/MV5BMjA2NTI1Mzg3N15BMl5BanBnXkFtZTcwMjYwNjAzMg@@._V1_.jpg',
    rate: '7.9',
    category: 'comedy',
  },
  {
    name: 'Titanic',
    year: 1997,
    img: 'https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SY1000_CR0,0,671,1000_AL_.jpg',
    rate: '9.8',
    category: 'romance',
  },
  {
    name: 'The Notebook',
    year: 2004,
    img: 'https://m.media-amazon.com/images/M/MV5BMTk3OTM5Njg5M15BMl5BanBnXkFtZTYwMzA0ODI3._V1_.jpg',
    rate: '8.8',
    category: 'romance',
  },
  {
    name: 'Veer-Zaara',
    year: 2004,
    img: 'https://m.media-amazon.com/images/M/MV5BY2VlOTc4ZjctYjVlMS00NDYwLWEwZjctZmYzZmVkNGU5NjNjXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SY1000_CR0,0,721,1000_AL_.jpg',
    rate: '8.9',
    category: 'romance',
  },
];